### ISSUE TITLE
How to iterate uploaded files

### ISSUE THREAD

**Issue by v-bezborodov** [LukeTowers/oc-easyfiles-public-plugin#1]
What way to iterate uploaded files via Media Manager. Generally want share files to users from storage/app folder (only downloading). Placed in html next code.
```
[fileBrowser]
disk = "{{ storage }}"
folder = "{{ app }}"
includeStyles = 1
allowUploads = false
==
<!-- main -->
<?php foreach ($items as $item):
                $itemType = $item['getFileType'];//??
                echo $disk, $itemType;//???? had no idea what variable should be applied
?>
```
What am i doing wrong?

**Comment by LukeTowers** [comment]
@wenceslawus you're able to override any of the HTML generated by copying the files you wish to override from `/modules/backend/widgets/mediamanager/partials/` into `/themes/myactivetheme/partials/fileBrowser` (or replace `fileBrowser` with the specific alias you're using for a specific component instance).

Specifically if you just want a simple list of files then override the `_body.htm` partial by creating a file at `/themes/myactivetheme/partials/fileBrowser/_body.htm` and then doing the following:

```php
<ul>
    <?php foreach ($items as $item): ?>
        <li>
            <a href="<?= e($item->publicUrl) ?>"><?= e(basename($item->path)) ?> (<?= $item->getFileType(); ?>)</a>
        </li>
    <?php endforeach ?>
</ul>
```

Take a look at the rest of the partials available in `/modules/backend/widgets/mediamanager/partials/` to get an idea of what is available.

**Comment by LukeTowers** [comment]
Note, this code doesn't go on the page where you include the component, it goes in the paths I specified above, and then you render the component as normal with `{% component 'fileBrowser' %}. Additionally if you're using your own partials it's a good idea to disable the default styling with `includeStyles = 0`
