### ISSUE TITLE
Is there any opportunity to use symlinks?

### ISSUE THREAD

**Issue by sagjatome** [LukeTowers/oc-easyfiles-public-plugin#2]
Is there any opportunity to use symlinks?
I try to use this plugin to connect it with ownCloud.
Can you help with it?

**Comment by LukeTowers** [comment]
You can use this plugin with any storage driver supported by Laravel. I'm not sure if any Laravel storage drivers support symlinks or what your exact situation requires. Per our emailed conversation there is https://github.com/coraxster/laravel-owncloud to connect to an OwnCloud instance and if you would like to hire me for custom integration help my current rates are $150 USD/hr.

**Comment by sagjatome** [comment]
Thank you for the proposition.
We have found already the solution.
I wish you all the best.


Mit freundlichen Grüßen
Yevhen Melnyk
Emder Str. 9
26603 Aurich
Tel.: (0176) 949-14311
Fax: (04941) 962-4992
